[project]
name = "vcli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.2.0",
    "icecream>=2.1.4",
    "pandas>=2.2.3",
    "seaborn>=0.13.2",
]
